title: 摄影与孤独| The Independent Photographer｜木子欢儿的艺术集
author: muzihuaner
email: muzihuaner@hotmail.com
description: >-
  一个普遍的误解是，所有摄影师都是具有超凡魅力的，外向的社交名流，他们可以在任何情况下进行自我讨论。 通常，艺术过程会在寂寞的时光中展开。 孤独和纪律可以提高艺术创作的效率，尽管孤独可能具有挑战性和孤独感，但如伯格曼所言，独自工作的决定也是转而面对我们所有人固有的情感，面对自己的人性。

social:
  twitter: muzihuaner
  facebook: muzihuaner
  instagram: muzihuaner
  github: muzihuaner
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
